import {useState} from 'react';
import {Camera, Aperture, ArrowRight} from 'lucide-react';
import {SiteLink} from './LocationPages';
import {PRODUCTS,BRANDS,BUDGETS,BUYING_NOTES,CHECKED} from './data/gearGuide';
import './styles/gear-guide.css';
const money=n=>n==null?'가격 확인 필요':`${n.toLocaleString('ko-KR')}원`;
const purposes=['입문','일상','인물','여행','영상','망원','접사'];
function Product({p,selected,toggle,disabled}){return <article className="gear-card"><div className="gear-card-top"><span>{p.brand} / {p.kind}</span>{p.kind==='카메라'?<Camera/>:<Aperture/>}</div><h3>{p.name}</h3><p className="gear-spec">{p.mount} 마운트 · {p.sensor}{p.kind==='렌즈'?' 대응':''}</p><strong className="gear-price">{money(p.price)}{p.basis.includes('시작가')&&'부터'}</strong><small>{p.basis} · {CHECKED} 확인</small><div className="gear-tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><p>{p.good}</p><details><summary>구매 전에 볼 점</summary><p>{p.caution}</p><a href={p.url} target="_blank" rel="noreferrer">공식 정보·가격 출처 ↗</a></details><button className="gear-compare-button" aria-pressed={selected} disabled={disabled&&!selected} onClick={()=>toggle(p.id)}>{selected?'✓ 비교에서 빼기':`${p.name} 비교 담기`}</button></article>;}
function Catalog(){const [kind,setKind]=useState('카메라'),[brand,setBrand]=useState(''),[purpose,setPurpose]=useState(''),[budget,setBudget]=useState(''),[mount,setMount]=useState(''),[q,setQ]=useState(''),[compare,setCompare]=useState([]);
 const reset=()=>{setBrand('');setPurpose('');setBudget('');setMount('');setQ('');};
 const results=PRODUCTS.filter(p=>p.kind===kind&&(!brand||p.brand===brand)&&(!purpose||p.tags.includes(purpose))&&(!mount||p.mount===mount)&&(!budget||(p.price!=null&&p.price<=Number(budget)))&&`${p.name} ${p.brand} ${BRANDS.find(b=>b.id===p.brand)?.name} ${p.good}`.toLowerCase().includes(q.toLowerCase()));
 const picked=compare.map(id=>PRODUCTS.find(p=>p.id===id));
 const toggle=id=>setCompare(old=>old.includes(id)?old.filter(x=>x!==id):old.length<3?[...old,id]:old);
 return <><div className="gear-section-heading"><div><p className="eyebrow">FIND YOUR EVERYDAY COMPANION</p><h2>내가 찍고 싶은 장면부터.</h2></div><span>카메라 13종 · 렌즈 12종</span></div><div className="learn-filter">{['카메라','렌즈'].map(t=><button key={t} aria-pressed={kind===t} onClick={()=>{setKind(t);reset();setCompare([]);}}>{t} 찾기</button>)}</div><div className="gear-filters"><label>제품 검색<input value={q} onChange={e=>setQ(e.target.value)} placeholder="R50, 소니, 50mm…"/></label><label>브랜드<select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">모든 브랜드</option>{BRANDS.filter(b=>PRODUCTS.some(p=>p.kind===kind&&p.brand===b.id)).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>촬영 목적<select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="">모든 목적</option>{purposes.map(t=><option key={t}>{t}</option>)}</select></label><label>제품 예산 상한<select value={budget} onChange={e=>setBudget(e.target.value)}><option value="">금액 제한 없음</option>{[500000,1000000,1500000,2000000,2500000,4000000].map(n=><option key={n} value={n}>{n/10000}만 원 이하</option>)}</select></label><label>마운트<select value={mount} onChange={e=>setMount(e.target.value)}><option value="">모든 마운트</option>{['RF','E','X','Z'].map(t=><option key={t}>{t}</option>)}</select></label></div><div className="gear-result-line"><p role="status">{results.length}개 제품{budget?' · 가격이 확인된 제품만 표시':''}</p><button onClick={reset}>조건 초기화</button></div><p className="gear-footnote">추천 이유는 365의 편집 의견입니다. 가격은 공식 참고값이며 실시간 판매가·최저가가 아닙니다. 시작가는 선택 구성에 따라 달라지고, 바디만인 제품은 렌즈 비용이 추가됩니다. 재고와 최종 결제 금액은 판매처에서 확인하세요.</p><div className="gear-grid">{results.map(p=><Product key={p.id} p={p} selected={compare.includes(p.id)} toggle={toggle} disabled={compare.length===3}/>)}</div>{!results.length&&<div className="learn-empty"><h3>이 조건에 맞는 제품이 없어요.</h3><p>예산이나 브랜드 조건을 넓혀보세요.</p><button className="button ghost" onClick={reset}>전체 제품 보기</button></div>}<section className="gear-comparison" aria-label="제품 비교"><div className="gear-section-heading"><h2>나란히 놓고 비교해요.</h2><span aria-live="polite">{picked.length} / 3개 선택</span></div>{!picked.length?<p>제품 카드에서 ‘비교 담기’를 누르면 특징과 가격을 함께 볼 수 있어요.</p>:<><div className="gear-table-scroll" tabIndex={0} aria-label="제품 비교표 가로 스크롤"><table><caption>{kind} 비교 · 바디 / 키트 / 시작가 기준을 함께 확인하세요</caption><thead><tr><th scope="col">비교 항목</th>{picked.map(p=><th scope="col" key={p.id}>{p.name}<button aria-label={`${p.name} 비교 제거`} onClick={()=>toggle(p.id)}>제거</button></th>)}</tr></thead><tbody>{[['공식 참고가격',p=>money(p.price)],['가격 기준',p=>p.basis],['마운트',p=>p.mount],['센서 / 대응 영역',p=>p.sensor],['추천 장면',p=>p.tags.join(' · ')],['선택 이유',p=>p.good],['살펴볼 점',p=>p.caution]].map(([label,get])=><tr key={label}><th scope="row">{label}</th>{picked.map(p=><td key={p.id}>{get(p)}</td>)}</tr>)}</tbody></table></div><button className="button ghost" onClick={()=>setCompare([])}>비교 비우기</button></>}</section></>;
}
function Compatibility(){const [body,setBody]=useState('r50'),[lens,setLens]=useState('rf85');const a=PRODUCTS.find(p=>p.id===body),b=PRODUCTS.find(p=>p.id===lens);const result=a.mount!==b.mount?'마운트가 달라 직접 장착할 수 없어요.':a.sensor==='풀프레임'&&b.sensor==='APS-C'?'같은 마운트지만 APS-C용 렌즈예요. 크롭 모드·기록 화소와 기종별 지원을 확인하세요.':'같은 마운트이며 센서 대응 영역도 맞아요. 최종 AF·보정 지원은 해당 카메라 설명서에서 확인하세요.';return <section className="gear-compat"><p className="eyebrow">BEFORE YOU ADD A LENS</p><h2>내 카메라에 맞는 렌즈일까?</h2><p>아래는 어댑터 없이 결합하는 경우의 마운트·센서 기준 안내입니다.</p><div className="gear-filters"><label>카메라<select aria-label="호환 확인 카메라" value={body} onChange={e=>setBody(e.target.value)}>{PRODUCTS.filter(p=>p.kind==='카메라').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>렌즈<select aria-label="호환 확인 렌즈" value={lens} onChange={e=>setLens(e.target.value)}>{PRODUCTS.filter(p=>p.kind==='렌즈').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><p className="gear-compat-result" role="status">{result}</p></section>;}
export default function GearGuide({slug,language,navigate}){const isBrand=slug==='brands',isBudget=slug==='budget';return <section className="section-wrap gear-page"><header className="gear-hero"><div><p className="eyebrow">365 / THE GEAR SHELF</p><h1>{isBrand?'브랜드보다, 나에게 맞는 시스템.':isBudget?'첫 장비, 예산부터 차근차근.':<>어떤 카메라로<br/><em>나의 하루를 담을까.</em></>}</h1><p>처음 사는 카메라부터 다음 렌즈까지.<br/>이름과 숫자 뒤에 있는 차이를 쉬운 말로 알아봐요.</p></div><div className="gear-hero-note"><Aperture size={64}/><span>START WITH YOUR STORY</span><p>좋은 장비는<br/>자주 들고 나가는 장비.</p><small>제품 25종 / 브랜드 7곳 / 예산 구성 4가지</small></div></header><nav className="gear-subnav" aria-label="장비 가이드 메뉴">{[['gear','카메라·렌즈 찾기'],['budget','예산별 입문 가이드'],['brands','브랜드 알아보기']].map(([id,t])=><SiteLink key={id} navigate={navigate} href={`/${language}/learn/${id}`} aria-current={slug===id?'page':undefined}>{t}<ArrowRight size={16}/></SiteLink>)}</nav>{isBrand?<><div className="gear-grid brand-grid">{BRANDS.map(b=><article className="gear-card" key={b.id}><p className="eyebrow">{b.id}</p><h2>{b.name}</h2><span className="gear-spec">{b.mount}</span><p>{b.about}</p><div className="gear-caution">{b.caution}</div><a href={b.url} target="_blank" rel="noreferrer">공식 시스템 살펴보기 ↗</a></article>)}</div><Compatibility/></>:isBudget?<><p className="gear-footnote">아래 구성은 확인된 렌즈 키트 가격으로 계산한 예시입니다. 시장 전체의 순위가 아니며, 구성에 맞춰 다른 브랜드도 제품 목록에서 비교해보세요. 액세서리 금액은 실제 제품 가격이 아닌 계획용 여유 예산입니다.</p><div className="gear-grid budget-grid">{BUDGETS.map(b=>{const p=PRODUCTS.find(x=>x.id===b.product);return <article className="gear-card" key={b.product}><p className="eyebrow">FIRST KIT</p><h2>{b.title}</h2><h3>{p.name}</h3><p>{b.text}</p><dl><div><dt>카메라 + 포함 렌즈</dt><dd>{money(p.price)}</dd></div><div><dt>액세서리 여유 예산</dt><dd>{money(b.reserve)}</dd></div><div><dt>계획 합계</dt><dd><strong>{money(p.price+b.reserve)}</strong></dd></div></dl><small>{p.basis} · {CHECKED} 확인</small><a href={p.url} target="_blank" rel="noreferrer">가격 근거 확인 ↗</a></article>;})}</div><h2 className="gear-notes-heading">사기 전에 알면 좋은 12가지.</h2><div className="gear-notes">{BUYING_NOTES.map(([title,text],i)=><details key={title}><summary><span>{String(i+1).padStart(2,'0')}</span>{title}</summary><p>{text}</p></details>)}</div></>:<><Catalog/><Compatibility/></>}<footer className="gear-learning-links"><h2>장비의 숫자가 아직 낯설다면.</h2><p>화각과 노출 실험실에서 먼저 움직여보세요. 어떤 렌즈가 필요한지 더 쉽게 알 수 있어요.</p><SiteLink className="button primary" href={`/${language}/learn/labs`} navigate={navigate}>화각·노출 직접 해보기 <ArrowRight/></SiteLink><SiteLink className="text-link" href={`/${language}/learn/equipment`} navigate={navigate}>장비 기초 읽기 →</SiteLink></footer></section>;}
