import { useId, useState } from 'react';

const APERTURES=[1.8,2.8,4,5.6,8,11,16];
const SHUTTERS=[15,30,60,125,250,500,1000];
const ISOS=[100,200,400,800,1600,3200,6400];
function Choice({label,value,items,onChange}) { return <fieldset className="lab-choice"><legend>{label}</legend><div>{items.map(([v,t])=><button type="button" key={v} aria-pressed={value===v} onClick={()=>onChange(v)}>{t}</button>)}</div></fieldset>; }
function Range({label,value,onChange,values,format,help}) { const id=useId();return <div className="lab-range"><label htmlFor={id}>{label}<strong>{format(values[value])}</strong></label><input id={id} type="range" min="0" max={values.length-1} step="1" value={value} aria-valuetext={format(values[value])} onChange={e=>onChange(Number(e.target.value))}/><div><span>{format(values[0])}</span><span>{format(values.at(-1))}</span></div><p>{help}</p></div>; }

function Person({x=360,y=355,size=1,color='#725243',opacity=1}) {return <g transform={`translate(${x} ${y}) scale(${size})`} fill={color} opacity={opacity}><path d="M-23-121Q-33-91-31-60L-39-5Q-34 3-26 0L-6-57 6-57 26 0Q34 3 39-5L31-60Q33-91 23-121Z"/><circle cy="-148" r="21"/><path d="M-25-112L-57-64M25-112L57-64" fill="none" stroke={color} strokeWidth="13" strokeLinecap="round"/></g>;}

export function ExposureLab(){
  const [a,setA]=useState(2),[s,setS]=useState(3),[i,setI]=useState(2);
  const uid=useId().replaceAll(':','');
  const f=APERTURES[a], speed=SHUTTERS[s],iso=ISOS[i];
  const relative=(4/f)**2*(125/speed)*(iso/400),ev=Math.log2(relative);
  const blur=Math.max(0,(8-f)*.65), motion=Math.max(0,125/speed-1)*4;
  const preset=(a,s,i)=>{setA(a);setS(s);setI(i);};
  return <section className="learning-lab" aria-label="노출 3요소 실험실"><header><div><p className="eyebrow">LAB 01 / EXPOSURE</p><h2>세 가지를 바꾸면, 사진은?</h2></div><button className="lab-reset" onClick={()=>preset(2,3,2)}>처음 설정으로 ↺</button></header><p className="lab-intro">같은 빛 아래에서 한 가지씩 바꿔보세요. 자동 노출 보정은 꺼져 있다고 가정합니다.</p><div className="lab-layout"><div><div className="exposure-scene"><svg viewBox="0 0 720 440" role="img" aria-label={`개념 그림: 조리개 f/${f}, 셔터 1/${speed}초, ISO ${iso}. 기준 대비 ${ev.toFixed(1)}스톱.`}>
    <defs><filter id={`${uid}-blur`}><feGaussianBlur stdDeviation={blur}/></filter><filter id={`${uid}-noise`}><feTurbulence type="fractalNoise" baseFrequency=".8" numOctaves="2" seed="12" stitchTiles="stitch"/></filter></defs>
    <g style={{filter:`brightness(${Math.max(.15,Math.min(2.7,relative**.45))})`}}><rect width="720" height="440" fill="#d4dedb"/><g filter={`url(#${uid}-blur)`}><circle cx="568" cy="74" r="36" fill="#f4e8c1"/><path d="M0 190L120 100 240 180 350 115 500 202 610 134 720 190V440H0Z" fill="#9daa94"/><rect y="245" width="720" height="195" fill="#c4ba99"/>{[75,190,550,650].map(x=><g key={x}><rect x={x-6} y="178" width="12" height="145" fill="#82715a"/><ellipse cx={x} cy="173" rx="50" ry="78" fill="#768975"/></g>)}<path d="M325 245H390L580 440H130Z" fill="#ddd1b5"/></g>{motion>0 && [1,2,3].map(n=><Person key={n} x={360-motion*n} opacity={.11} />)}<Person/><ellipse cx="360" cy="365" rx="65" ry="9" fill="#796651" opacity=".18"/></g>
    <rect width="720" height="440" filter={`url(#${uid}-noise)`} opacity={i*.035} style={{mixBlendMode:'soft-light'}}/>{relative>4&&<rect width="720" height="440" fill="white" opacity={Math.min(.6,(relative-4)/40)}/>}</svg><span>설명용 그림 · 실제 카메라 결과와 다릅니다</span></div><div className="lab-reading" aria-live="polite"><strong>{Math.abs(ev)<.15?'기준과 비슷한 밝기':ev>0?'기준보다 밝아져요':'기준보다 어두워져요'}</strong><span>{ev>0?'+':''}{ev.toFixed(1)} stop</span></div><p className="lab-small">기준: f/4 · 1/125초 · ISO 400. 밝기·흐림·노이즈 변화는 이해를 돕기 위해 단순화했습니다. 심도는 촬영 거리와 렌즈에도 영향을 받아요.</p></div><div className="lab-controls">
    <Range label="조리개" value={a} onChange={setA} values={APERTURES} format={v=>`f/${v}`} help="작은 F 숫자 → 빛을 더 통과시켜요. 같은 조건에서는 배경을 흐리기 쉬워요."/>
    <Range label="셔터속도" value={s} onChange={setS} values={SHUTTERS} format={v=>`1/${v}초`} help="짧은 시간 → 움직임을 멈추기 좋아요. 대신 모으는 빛이 줄어요."/>
    <Range label="ISO" value={i} onChange={setI} values={ISOS} format={v=>String(v)} help="높은 ISO → 같은 빛 기록을 보통 더 밝게 표현해요. 빛 자체가 늘지는 않아요."/>
    <div className="lab-presets"><span>비슷한 밝기, 다른 표현</span><button onClick={()=>preset(2,6,5)}>움직임 멈추기</button><button onClick={()=>preset(4,1,2)}>움직임 남기기</button></div></div></div></section>;
}

export function LensLab(){
  const [focal,setFocal]=useState(35),[crop,setCrop]=useState(1),[mode,setMode]=useState('fixed');
  const sensor=36/crop, distance=mode==='fixed'?8:8*focal*crop/35;
  const scale=z=>focal/sensor*720/z;
  const angle=2*Math.atan(sensor/(2*focal))*180/Math.PI;
  const buildings=[[-8,4,3],[-4,6,2.6],[3.8,4.8,2.4],[7,3.5,3.4]];
  const bg=scale(distance+14),human=scale(distance);
  return <section className="learning-lab" aria-label="화각 비교 실험실"><header><div><p className="eyebrow">LAB 02 / FOCAL LENGTH</p><h2>렌즈를 바꿀까, 자리를 옮길까?</h2></div><button className="lab-reset" onClick={()=>{setFocal(35);setCrop(1);setMode('fixed');}}>처음 설정으로 ↺</button></header><p className="lab-intro">사람과 건물은 그대로 있어요. 먼저 같은 자리에서 렌즈만 바꿔보고, 다음에는 인물 크기를 맞춰보세요.</p>
    <div className="lab-layout"><div><div className="lens-scene"><svg viewBox="0 0 720 440" role="img" aria-label={`${focal}mm, ${crop===1?'풀프레임':'1.5배 APS-C'}, 인물까지 ${distance.toFixed(1)}미터. ${mode==='fixed'?'카메라 위치 고정':'인물 크기를 맞추며 카메라 이동'}`}><rect width="720" height="440" fill="#d9e2df"/><rect y="215" width="720" height="225" fill="#d1c5aa"/><path d="M345 215H375L650 440H70Z" fill="#e8ddc8"/>{buildings.map(([x,h,w],n)=><g key={x}><rect x={360+x*bg-w*bg/2} y={220+(1.5-h)*bg} width={w*bg} height={h*bg} fill={n%2?'#ad9c88':'#8c9b95'}/>{[.7,1.5,2.3].map(y=><rect key={y} x={360+x*bg-w*bg/3} y={220+(1.5-h+y)*bg} width={w*bg*.65} height={bg*.3} fill="#ece7d8" opacity=".65"/>)}</g>)}<Person x={360} y={220+1.5*human} size={1.7*human/169}/><path d="M345 220H375M360 205V235" stroke="#fff" strokeWidth="1" opacity=".6"/><text x="24" y="36" fill="#43544c" fontSize="16">{focal} mm / {crop===1?'FULL FRAME':'APS-C 1.5×'}</text></svg><span>원근 투영 개념도 · 렌즈 왜곡·심도는 생략</span></div><div className="lens-readings" aria-live="polite"><div><small>인물까지 거리</small><strong>{distance.toFixed(1)} m</strong></div><div><small>수평 화각</small><strong>{angle.toFixed(1)}°</strong></div><div><small>풀프레임 환산</small><strong>{Math.round(focal*crop)} mm</strong></div></div><p className="lab-small">풀프레임 센서 너비 36mm, APS-C 24mm를 가정합니다. APS-C 크롭 비율은 기종마다 다를 수 있어요. 건물은 인물보다 14m 뒤에 있습니다.</p></div>
    <div className="lab-controls"><Choice label="초점거리" value={focal} onChange={setFocal} items={[24,35,50,85,135].map(v=>[v,`${v}mm`])}/><Choice label="센서 크기" value={crop} onChange={setCrop} items={[[1,'풀프레임'],[1.5,'APS-C 1.5×']]}/><Choice label="비교 방법" value={mode} onChange={setMode} items={[[ 'fixed','같은 자리에서'],['match','인물 크기 맞추기']]}/><div className="lab-takeaway" aria-live="polite"><b>{mode==='fixed'?'위치는 그대로, 담기는 범위가 달라져요.':'인물은 같은 크기, 배경 크기가 달라져요.'}</b><p>{mode==='fixed'?'긴 초점거리일수록 화면의 좁은 부분을 크게 담습니다. 카메라가 움직이지 않아 원근 관계는 유지돼요.':'긴 초점거리에서는 카메라가 뒤로 이동합니다. 인물과 배경까지의 거리 비율이 바뀌면서 배경이 상대적으로 커 보여요.'}</p></div></div></div></section>;
}

export function CompositionLab(){
  const [rule,setRule]=useState('thirds'),[position,setPosition]=useState(66),[grid,setGrid]=useState(true);
  return <section className="learning-lab" aria-label="구도 실험실"><header><div><p className="eyebrow">LAB 03 / COMPOSITION</p><h2>주인공의 자리를 바꿔보세요.</h2></div><button className="lab-reset" onClick={()=>{setRule('thirds');setPosition(66);setGrid(true);}}>처음 설정으로 ↺</button></header><div className="lab-layout"><div><div className="composition-scene"><svg viewBox="0 0 720 440" role="img" aria-label={`인물이 화면 왼쪽에서 ${position}% 위치에 있는 구도 그림. ${grid?'삼분할 격자 표시':'격자 숨김'}`}><rect width="720" height="440" fill="#d6dfdb"/><rect y="285" width="720" height="155" fill="#b3b49c"/><circle cx="155" cy="100" r="42" fill="#f1dfb9"/>{rule==='lines'&&<g stroke="#eee1c8" strokeWidth="9"><path d={`M0 440L${position*7.2} 270M720 440L${position*7.2} 270`}/></g>}{rule==='frame'&&<g fill="#78897b"><rect width="60" height="440"/><rect x="660" width="60" height="440"/><rect width="720" height="55"/></g>}<Person x={position*7.2} y={375} size={1.25}/>{grid&&<g stroke="#fff" opacity=".75" strokeWidth="1" strokeDasharray="5 5"><path d="M240 0V440M480 0V440M0 146.7H720M0 293.3H720"/></g>}</svg></div><p className="lab-small">실제 촬영에서도 카메라를 좌우로 움직여 배경과 주인공의 관계를 살펴보세요. 선은 참고이며 정답은 아닙니다.</p></div><div className="lab-controls"><Choice label="구도 아이디어" value={rule} onChange={v=>{setRule(v);setPosition(v==='center'||v==='frame'?50:v==='space'?30:66);}} items={[[ 'thirds','삼분할'],['center','중앙'],['space','여백'],['lines','유도선'],['frame','프레임']]}/><div className="lab-range"><label htmlFor="subject-position">주인공 위치<strong>{position}%</strong></label><input id="subject-position" type="range" min="15" max="85" value={position} onChange={e=>setPosition(Number(e.target.value))}/><p>왼쪽과 오른쪽으로 움직이며 시선이 어디에 머무는지 보세요.</p></div><label className="grid-toggle"><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/>삼분할 격자 보기</label><div className="lab-takeaway"><b>{({thirds:'중심에서 조금 벗어나도 좋아요.',center:'가운데에 놓으면 존재감이 또렷해져요.',space:'비워둔 곳에도 이야기가 생겨요.',lines:'선이 시선을 주인공 쪽으로 안내해요.',frame:'사진 안에 작은 틀을 만들어보세요.'})[rule]}</b><p>구도는 시선을 안내하는 도구예요. 같은 장면을 여러 방식으로 담고 자신의 의도에 맞는 것을 골라보세요.</p></div></div></div></section>;
}
