import { useState } from 'react';
import { ArrowRight, ArrowLeft, BookOpen, Check, Search } from 'lucide-react';
import { SiteLink } from './LocationPages';
import { LESSONS, GLOSSARY, PHOTO_SOURCES } from './data/photoLessons';
import { ExposureLab, LensLab, CompositionLab } from './LearningLabs';
import './styles/learning.css';
import GearGuide from './GearGuide';

const GROUPS=[...new Set(LESSONS.map(l=>l.group))];
const LABS={exposure:ExposureLab,lens:LensLab,composition:CompositionLab};
const PROGRESS_KEY='365-photo-lessons-v1';
const normalize=s=>s.toLowerCase().replace(/\s|·|\//g,'');
function Quiz({quiz}){const [answer,setAnswer]=useState(null);return <section className="learn-quiz"><p className="eyebrow">ONE SMALL CHECK</p><h2>{quiz.q}</h2><div>{quiz.options.map((text,i)=><button type="button" key={text} aria-pressed={answer===i} onClick={()=>setAnswer(i)}><span>{i+1}</span>{text}</button>)}</div>{answer!==null&&<p role="status"><b>{answer===quiz.answer?'맞아요.':'다시 생각해볼까요?'}</b> {answer===quiz.answer?quiz.why:'설명으로 돌아가 확인하거나 다른 답을 골라보세요.'}</p>}</section>;}
function LearningNav({slug,language,navigate}){return <nav className="learning-nav section-wrap" aria-label="사진 배우기 메뉴">{[['','배움의 순서'],['labs','직접 해보기'],['glossary','용어 사전'],['gear','장비 가이드']].map(([id,t])=><SiteLink key={id} navigate={navigate} href={`/${language}/learn${id?'/'+id:''}`} aria-current={(slug===id||(id==='gear'&&['budget','brands'].includes(slug)))?'page':undefined}>{t}</SiteLink>)}<span>처음부터, 천천히.</span></nav>;}
function Sources(){return <details className="learn-sources"><summary>더 읽어보기 · 개념 참고 자료</summary><p>설명과 그림은 입문 학습을 위해 직접 구성했습니다. 장비별 조작·기능은 해당 제품 설명서도 확인하세요.</p>{PHOTO_SOURCES.map(([title,url])=><a key={url} href={url} target="_blank" rel="noreferrer">{title} ↗</a>)}</details>;}
function Overview({language,navigate,done}){
  const [query,setQuery]=useState(''),[group,setGroup]=useState('');
  const filtered=LESSONS.filter(l=>(!group||l.group===group)&&normalize([l.title,l.intro,...l.concepts.flat()].join(' ')).includes(normalize(query)));
  const next=LESSONS.find(l=>!done.includes(l.id))||LESSONS[0];
  return <><section className="section-wrap learning-hero"><div><p className="eyebrow">THE PHOTO NOTEBOOK / BEGINNER FRIENDLY</p><h1>사진, 어렵지 않게.<br/><em>한 장씩 알아가요.</em></h1><p>빛을 보고, 주인공을 정하고, 셔터를 눌러보세요.<br/>처음에는 모든 숫자를 외우지 않아도 괜찮아요.</p><div className="learning-hero-actions"><SiteLink className="button primary" href={`/${language}/learn/${next.id}`} navigate={navigate}>{done.length?'이어서 배우기':'처음부터 배우기'}<ArrowRight/></SiteLink><SiteLink className="text-link" href={`/${language}/learn/labs`} navigate={navigate}>눈으로 비교해보기 ↗</SiteLink></div><div className="learn-progress"><span>{done.length} / {LESSONS.length} 주제 읽음</span><progress max={LESSONS.length} value={done.length} aria-label="학습 진행"/></div></div><div className="notebook-cover" aria-label="사진 배우기 노트: 빛, 시간, 시선"><div><span>365 / FIELD NOTES</span><BookOpen/></div><svg viewBox="0 0 340 275" role="img" aria-label="빛과 시간, 시선이 모여 한 장의 사진이 되는 개념 그림"><circle cx="170" cy="135" r="99" fill="none" stroke="#d5c5a6" strokeWidth="1"/><circle cx="170" cy="135" r="68" fill="none" stroke="#d5c5a6" strokeWidth="1"/><path d="M170 36L256 185H84Z" stroke="#d5c5a6" fill="none"/><circle cx="170" cy="135" r="29" fill="#d5c5a6"/><text x="170" y="18">빛</text><text x="58" y="216">시간</text><text x="282" y="216">시선</text></svg><p>LOOK. TRY. MAKE.</p><span>작은 이해가 쌓여, 나다운 사진으로.</span></div></section>
  <section className="section-wrap learn-practice"><div><p className="eyebrow">THE GEAR SHELF</p><h2>첫 카메라, 다음 렌즈가 궁금하다면.</h2><p>카메라·렌즈 25종 비교부터 예산별 입문 구성, 브랜드와 마운트까지 쉬운 말로 알아보세요.</p></div><SiteLink className="button ghost" href={`/${language}/learn/gear`} navigate={navigate}>장비 가이드 보기 <ArrowRight/></SiteLink></section>
  <section className="section-wrap learning-start"><div><span className="eyebrow">YOUR FIRST FIVE MINUTES</span><h2>처음이라면 이 순서로.</h2></div><ol>{[['start','주인공 정하기'],['exposure','밝기 이해하기'],['lenses','담기는 범위 보기'],['composition','구도 바꿔보기']].map(([id,title],i)=><li key={id}><SiteLink href={`/${language}/learn/${id}`} navigate={navigate}><span>0{i+1}</span><b>{title}</b><ArrowRight/></SiteLink></li>)}</ol></section>
  <section className="section-wrap learning-library"><div className="learn-section-heading"><div><p className="eyebrow">A LITTLE AT A TIME</p><h2>궁금한 것부터 펼쳐보세요.</h2></div><span>{LESSONS.length}개 주제 · {GLOSSARY.length}개 용어와 개념</span></div><div className="learning-search"><Search/><input aria-label="학습 주제 검색" placeholder="조리개, 렌즈, 구도, RAW…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="learn-filter" aria-label="학습 분류">{['',...GROUPS].map(g=><button key={g} type="button" aria-pressed={group===g} onClick={()=>setGroup(g)}>{g||'전체'}</button>)}</div><p className="learn-count" role="status">{filtered.length}개 주제</p><div className="lesson-grid">{filtered.map(l=><SiteLink key={l.id} href={`/${language}/learn/${l.id}`} navigate={navigate} className="lesson-card"><div><span>{String(LESSONS.indexOf(l)+1).padStart(2,'0')}</span><small>{l.group} · 약 {l.minutes}분</small></div><h3>{l.title}</h3><p>{l.intro}</p><footer><span>{done.includes(l.id)?'✓ 읽은 주제':l.lab?'직접 해보기 포함':`${l.concepts.length}개 개념`}</span><ArrowRight/></footer></SiteLink>)}</div>{!filtered.length&&<div className="learn-empty"><p>검색한 주제가 없어요. 다른 단어나 분류로 찾아보세요.</p><button className="button ghost" onClick={()=>{setQuery('');setGroup('');}}>전체 주제 보기</button></div>}</section>
  <section className="section-wrap learn-practice"><div><p className="eyebrow">TODAY'S SMALL MISSION</p><h2>같은 물건, 세 가지 배경.</h2><p>카메라나 스마트폰으로 같은 물건을 찍어보세요. 설정은 그대로 두고 배경만 바꿔도 사진의 분위기가 달라집니다.</p></div><SiteLink className="button ghost" href={`/${language}/locations`} navigate={navigate}>연습할 장소 찾기 <ArrowRight/></SiteLink></section></>;
}
function Glossary({language,navigate}){const [q,setQ]=useState(''),[group,setGroup]=useState('');const results=GLOSSARY.filter(t=>(!group||t.group===group)&&normalize(t.term+' '+t.meaning).includes(normalize(q)));return <section className="section-wrap glossary-page"><p className="eyebrow">WORDS, MADE SIMPLE</p><h1>사진 용어, 쉬운 말로.</h1><p className="learn-lede">처음 듣는 말이 있어도 괜찮아요. 뜻을 확인하고 관련 수업에서 직접 만나보세요.</p><div className="glossary-tools"><div className="learning-search"><Search/><input aria-label="사진 용어 검색" placeholder="ISO, 보케, 화각, RAW…" value={q} onChange={e=>setQ(e.target.value)}/></div><select aria-label="용어 분류" value={group} onChange={e=>setGroup(e.target.value)}><option value="">모든 분류</option>{GROUPS.map(g=><option key={g}>{g}</option>)}</select></div><p className="learn-count" role="status">{results.length}개 용어와 개념</p><dl className="glossary-list">{results.map(t=><div key={t.term}><dt>{t.term}<small>{t.group}</small></dt><dd><p>{t.meaning}</p><SiteLink href={`/${language}/learn/${t.lesson}`} navigate={navigate}>관련 주제 배우기 <ArrowRight/></SiteLink></dd></div>)}</dl>{!results.length&&<div className="learn-empty"><p>일치하는 용어가 없어요.</p><button className="button ghost" onClick={()=>{setQ('');setGroup('');}}>전체 용어 보기</button></div>}<Sources/></section>;}
function LabPage(){const [tab,setTab]=useState('exposure');const Lab=LABS[tab];return <section className="section-wrap learn-labs-page"><p className="eyebrow">THE SMALL PHOTO LAB</p><h1>바꿔보면, 이해가 쉬워져요.</h1><p className="learn-lede">실제 사진을 흉내 낸 정답이 아니라, 변화의 방향을 이해하는 개념 실험실입니다.</p><div className="learn-filter" aria-label="실험실 선택">{[['exposure','노출 3요소'],['lens','화각·렌즈'],['composition','구도']].map(([id,title])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{title}</button>)}</div><Lab key={tab}/><Sources/></section>;}
function Lesson({lesson,language,navigate,done,onToggle}){const index=LESSONS.indexOf(lesson),next=LESSONS[index+1],prev=LESSONS[index-1],Lab=LABS[lesson.lab];return <><div className="section-wrap learn-breadcrumb"><SiteLink href={`/${language}/learn`} navigate={navigate}><ArrowLeft/> 전체 주제</SiteLink><span>{lesson.group} / {String(index+1).padStart(2,'0')}</span></div><article className="section-wrap lesson-page"><header className="lesson-heading"><p className="eyebrow">PHOTO NOTE {String(index+1).padStart(2,'0')} / 약 {lesson.minutes}분</p><h1>{lesson.title}</h1><p>{lesson.intro}</p></header><div className="lesson-body"><aside className="lesson-outline"><p className="eyebrow">IN THIS NOTE</p><ol>{lesson.concepts.map(([title],i)=><li key={title}><a href={`#concept-${i}`}>{title}</a></li>)}</ol>{Lab&&<a href="#lesson-lab" className="text-link">직접 비교해보기 ↓</a>}</aside><div className="lesson-concepts">{lesson.concepts.map(([title,text,task],i)=><section key={title} id={`concept-${i}`}><small>0{i+1}</small><h2>{title}</h2><p>{text}</p><div className="tiny-task"><b>작게 해보기</b><p>{task}</p></div></section>)}<aside className="learn-misconception"><span>헷갈리기 쉬워요</span><p>{lesson.misconception}</p></aside></div></div>{Lab&&<div id="lesson-lab"><Lab/></div>}{lesson.quiz&&<Quiz key={lesson.id} quiz={lesson.quiz}/>}<div className="lesson-complete"><div><h2>오늘은 여기까지 알아도 충분해요.</h2><p>하나만 기억하고 한 장 찍어보세요. 읽음 표시는 이 브라우저에 저장합니다.</p></div><button type="button" className={`button ${done?'ghost':'primary'}`} aria-pressed={done} onClick={()=>onToggle(lesson.id)}>{done?<><Check/> 읽음 표시 취소</>:<>읽음으로 표시 <Check/></>}</button></div><nav className="lesson-pagination" aria-label="이전 다음 학습">{prev?<SiteLink href={`/${language}/learn/${prev.id}`} navigate={navigate}><small>← 이전 주제</small><b>{prev.title}</b></SiteLink>:<SiteLink href={`/${language}/learn`} navigate={navigate}>전체 주제로 돌아가기</SiteLink>}{next?<SiteLink href={`/${language}/learn/${next.id}`} navigate={navigate}><small>다음 주제 →</small><b>{next.title}</b></SiteLink>:<SiteLink href={`/${language}/learn/labs`} navigate={navigate}>실험실에서 복습하기 →</SiteLink>}</nav><Sources/></article></>;}

export default function LearningCenter({slug,language,navigate}){
  const [done,setDone]=useState(()=>{try{const value=JSON.parse(localStorage.getItem(PROGRESS_KEY)||'[]');return Array.isArray(value)?value.filter(id=>LESSONS.some(l=>l.id===id)):[];}catch{return [];}});
  const toggle=id=>setDone(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];try{localStorage.setItem(PROGRESS_KEY,JSON.stringify(next));}catch{/* Reading is available even when storage is blocked. */}return next;});
  const lesson=LESSONS.find(l=>l.id===slug);
  return <main className="learning-center"><LearningNav slug={slug} language={language} navigate={navigate}/>{['gear','brands','budget'].includes(slug)?<GearGuide key={slug} slug={slug} language={language} navigate={navigate}/>:!slug?<Overview language={language} navigate={navigate} done={done}/>:slug==='glossary'?<Glossary language={language} navigate={navigate}/>:slug==='labs'?<LabPage/>:lesson?<Lesson key={lesson.id} lesson={lesson} language={language} navigate={navigate} done={done.includes(lesson.id)} onToggle={toggle}/>:<section className="section-wrap learn-empty"><h1>이 학습 주제를 찾지 못했어요.</h1><SiteLink href={`/${language}/learn`} navigate={navigate}>전체 주제 보기 →</SiteLink></section>}</main>;
}
