import { Heart, Sparkles, UserRound, UsersRound } from "lucide-react";

export const COPY = {
  ko: {
    languageName: "한국어",
    title: "365 Daily Snap | 서울 인물 스냅·프로필 촬영",
    description: "서울·수도권을 중심으로 자연스러운 인물 스냅, 프로필, 커플 촬영과 포트폴리오 협업을 진행합니다.",
    nav: { work: "대표 작업", sessions: "촬영 안내", reviews: "후기", about: "작가 소개", faq: "FAQ", contact: "문의" },
    heroEyebrow: "SEOUL · CAPITAL AREA · TOKYO SELECTED DATES",
    heroTitle: "당신다운 순간이,\n오래 남는 장면이 되도록.",
    heroDescription: "억지로 만든 표정보다 대화와 움직임 속에서 드러나는 자연스러운 모습을 담습니다. 촬영이 처음이어도 포즈와 시선을 차분하게 안내해드립니다.",
    heroPrimary: "대표 작업 보기",
    heroSecondary: "촬영 상담하기",
    trust: ["촬영이 처음이어도 편안하게", "서울·수도권 중심", "공개 범위 사전 협의"],
    workEyebrow: "FEATURED PROJECTS",
    workTitle: "한 장의 결과보다, 그날의 분위기와 흐름까지.",
    workDescription: "같은 날 촬영한 장면을 하나의 프로젝트로 구성했습니다. 빛과 공간, 표정이 어떻게 이어지는지 천천히 살펴보세요.",
    viewProject: "프로젝트 보기",
    moreProjects: "프로젝트 더 보기",
    lessProjects: "접기",
    projectInquiry: "이 분위기로 상담하기",
    originalPost: "Instagram 원본 보기",
    whyEyebrow: "WHY 365 DAILY SNAP",
    whyTitle: "좋은 사진은, 편안한 촬영에서 시작됩니다.",
    whyItems: [
      { title: "서툴러도 자연스럽게", text: "포즈를 외울 필요 없습니다. 걷는 속도, 시선, 손의 위치부터 차분하게 안내합니다." },
      { title: "분위기에 맞는 장소 설계", text: "원하는 이미지와 이동 동선, 계절과 빛의 방향까지 고려해 장소와 시간대를 제안합니다." },
      { title: "나답게 보이는 보정", text: "피부톤과 색감, 배경의 방해 요소는 정돈하되 본래의 인상과 표정은 그대로 남깁니다." },
      { title: "공개 범위는 명확하게", text: "포트폴리오 공개 여부와 사용 범위를 촬영 전에 확인하며 비공개 촬영도 가능합니다." },
    ],
    sessionsEyebrow: "SESSIONS",
    sessionsTitle: "사진이 필요한 이유부터 함께 설계합니다.",
    sessionsDescription: "정형화된 구성보다 촬영 목적과 장소, 이동 시간, 보정 범위에 맞춰 필요한 내용을 상담 후 안내합니다.",
    sessions: [
      { icon: UserRound, name: "Portrait Snap", title: "개인 인물 스냅", time: "약 60분", text: "프로필과 SNS, 지금의 나를 남기기 위한 자연스러운 개인 촬영입니다.", tags: ["개인 프로필", "데일리", "SNS"] },
      { icon: UsersRound, name: "Couple Snap", title: "커플·데이트 스냅", time: "약 60~90분", text: "정해진 포즈보다 걷고 대화하는 흐름 속에서 두 사람다운 장면을 기록합니다.", tags: ["데이트", "기념일", "야외"] },
      { icon: Sparkles, name: "Portfolio", title: "프로필·브랜딩", time: "약 60~90분", text: "소개 페이지와 블로그, 업무용 프로필의 목적에 맞춰 이미지 방향을 함께 정리합니다.", tags: ["브랜딩", "업무 프로필", "콘셉트"] },
      { icon: Heart, name: "Collaboration", title: "포트폴리오 협업", time: "일정 협의", text: "서로의 작업 방향이 잘 맞는 경우, 콘셉트와 사용 범위를 합의한 뒤 TFP 협업을 진행합니다.", tags: ["TFP", "모델 협업", "사용 범위 협의"] },
    ],
    processEyebrow: "PROCESS",
    processTitle: "문의부터 전달까지, 흐름은 단순하고 안내는 분명하게.",
    process: [
      { number: "01", title: "문의", text: "희망 날짜와 지역, 촬영 목적, 마음에 둔 분위기를 알려주세요." },
      { number: "02", title: "방향 확정", text: "이동 동선과 빛, 의상과 활용 목적을 고려해 장소와 콘셉트를 정합니다." },
      { number: "03", title: "촬영", text: "대화하고 움직이며 가장 자연스러운 표정과 장면을 함께 만들어갑니다." },
      { number: "04", title: "셀렉·보정·전달", text: "후보 컷을 확인한 뒤 선택한 사진을 자연스럽게 보정해 온라인으로 전달합니다." },
    ],
    reviewsEyebrow: "REAL REVIEWS",
    reviewsTitle: "사진보다 먼저 기억되는, 촬영의 분위기",
    reviewsDescription: "실제로 함께 촬영한 분들이 남긴 이야기입니다. 결과물뿐 아니라 현장의 편안함과 소통 과정도 확인해보세요.",
    reviewOriginal: "후기 원본 보기",
    moreReviews: "후기 더 보기",
    aboutEyebrow: "ABOUT PHOTOGRAPHER",
    aboutTitle: "사람이 사진보다 먼저 편안해지는 순간을 기다립니다.",
    aboutText: "365 Daily Snap은 정해진 포즈를 반복하기보다 대화와 움직임 속에서 각자의 자연스러운 표정을 찾습니다. 사진이 익숙하지 않은 분도 부담 없이 촬영할 수 있도록 준비부터 현장 디렉팅, 셀렉과 전달까지 차분하게 안내합니다.",
    aboutFacts: ["서울·수도권 중심", "평일 저녁·주말 촬영", "개인·커플·프로필", "도쿄 선택 일정"],
    faqEyebrow: "FAQ",
    faqTitle: "촬영을 결정하기 전에 궁금한 것들",
    faqs: [
      { q: "사진이 처음이어도 괜찮나요?", a: "물론입니다. 포즈를 미리 준비할 필요 없이 걷는 방향, 시선, 손의 위치처럼 작은 움직임부터 현장에서 안내합니다." },
      { q: "원본도 받을 수 있나요?", a: "원본 전달 범위는 촬영 형태에 따라 사전에 안내합니다. 필요할 경우 후보 이미지를 공유하고 원하는 컷을 직접 선택하는 방식으로 진행할 수 있습니다." },
      { q: "보정은 어디까지 진행하나요?", a: "노출과 색감, 피부톤, 배경의 방해 요소를 자연스럽게 정리합니다. 얼굴형이나 체형을 크게 바꾸는 과도한 변형은 기본 보정에 포함하지 않습니다." },
      { q: "비공개 촬영도 가능한가요?", a: "가능합니다. 전체 공개, 일부 컷 공개, 비공개 중 원하는 범위를 촬영 전에 확인하고 그 기준에 맞춰 관리합니다." },
      { q: "비가 오면 어떻게 하나요?", a: "촬영 전날 예보를 함께 확인한 뒤 실내 장소로 변경하거나 일정을 다시 조율합니다." },
      { q: "촬영 장소도 추천받을 수 있나요?", a: "원하는 색감과 의상, 이동 가능한 지역, 촬영 목적을 바탕으로 어울리는 장소와 시간대를 제안합니다." },
    ],
    inquiryEyebrow: "CONTACT",
    inquiryTitle: "아직 콘셉트가 선명하지 않아도 괜찮습니다.",
    inquiryDescription: "희망 날짜와 지역, 촬영 목적만 먼저 알려주세요. 필요한 장면과 분위기는 대화를 통해 함께 구체화하겠습니다.",
    quick: "빠른 문의",
    detail: "상세 문의",
    step: "단계",
    next: "다음",
    previous: "이전",
    submit: "문의 보내기",
    sending: "문의 전송 중",
    form: {
      type: "촬영 유형",
      name: "이름 / 닉네임",
      contactMethod: "연락 방법",
      contact: "연락처 또는 계정",
      date: "희망 날짜",
      region: "희망 지역",
      mood: "원하는 분위기",
      purpose: "촬영 목적",
      people: "인원 수",
      privacy: "사진 공개 범위",
      reference: "참고 이미지",
      message: "추가 요청",
      consent: "문의 접수를 위한 개인정보 수집·이용에 동의합니다.",
    },
    placeholders: {
      name: "성함 또는 닉네임",
      contact: "@Instagram ID, 카카오톡 ID, 전화번호 또는 이메일",
      date: "예: 7월 둘째 주 주말 오후",
      region: "예: 성수, 연남, 일산",
      mood: "예: 담백한 필름 무드, 야간 시네마틱",
      purpose: "예: 개인 프로필, 커플 기념일, 포트폴리오",
      message: "걱정되는 점이나 꼭 남기고 싶은 장면을 적어주세요.",
    },
    types: ["개인 인물", "커플", "프로필·브랜딩", "포트폴리오 협업", "상담 후 결정"],
    contactMethods: ["Instagram DM", "카카오톡", "문자·전화", "이메일"],
    privacyOptions: ["상담 후 결정", "전체 공개 가능", "일부 컷만 공개", "비공개 희망"],
    uploadHint: "최대 3장, 장당 8MB 이하",
    consentDetail: "수집 항목: 이름, 연락처, 촬영 요청 정보 · 목적: 촬영 상담 및 일정 조율 · 보관: 상담 종료 후 1년 또는 요청 시 즉시 삭제",
    sent: "문의가 접수되었습니다. 내용을 확인한 뒤 선택하신 연락처로 답변드리겠습니다.",
    fallbackTitle: "문의 내용을 복사했습니다.",
    fallbackText: "현재 웹 저장 기능이 연결되지 않아 문의 내용을 클립보드에 복사했습니다. 카카오톡 또는 Instagram DM에 붙여넣어 보내주세요.",
    openKakao: "카카오톡으로 이동",
    openInstagram: "Instagram으로 이동",
    validation: "필수 항목과 개인정보 동의를 확인해주세요.",
    footerLine: "자연스러운 인물 스냅 · 서울 / 수도권 / 도쿄 선택 일정",
    privacy: "개인정보 처리 안내",
    close: "닫기",
    photoCount: "장",
  },
  ja: {
    languageName: "日本語",
    title: "365 Daily Snap | ソウル・東京 ポートレート撮影",
    description: "ソウル首都圏を中心に、自然なポートレート、プロフィール、カップル撮影を行います。東京は指定日程にてご相談いただけます。",
    nav: { work: "作品", sessions: "撮影案内", reviews: "レビュー", about: "プロフィール", faq: "FAQ", contact: "お問い合わせ" },
    heroEyebrow: "SEOUL · CAPITAL AREA · TOKYO SELECTED DATES",
    heroTitle: "あなたらしい瞬間を、\n長く残る一枚に。",
    heroDescription: "作り込んだ表情より、会話や動きの中に生まれる自然な姿を大切にしています。撮影が初めての方にも、ポーズや目線を落ち着いてご案内します。",
    heroPrimary: "代表作品を見る",
    heroSecondary: "撮影を相談する",
    trust: ["初めての撮影も安心", "ソウル首都圏中心", "公開範囲を事前確認"],
    workEyebrow: "FEATURED PROJECTS",
    workTitle: "一枚の完成写真だけでなく、その日の空気と流れまで。",
    workDescription: "同じ日に撮影した写真を一つのプロジェクトとしてまとめています。光、場所、表情のつながりをご覧ください。",
    viewProject: "プロジェクトを見る",
    moreProjects: "もっと見る",
    lessProjects: "閉じる",
    projectInquiry: "この雰囲気で相談する",
    originalPost: "Instagramで見る",
    whyEyebrow: "WHY 365 DAILY SNAP",
    whyTitle: "良い写真は、安心できる撮影から始まります。",
    whyItems: [
      { title: "慣れていなくても自然に", text: "ポーズを覚える必要はありません。歩く速さ、目線、手の位置から丁寧にご案内します。" },
      { title: "雰囲気に合う場所選び", text: "希望するイメージ、移動範囲、季節や光を考えながら場所と時間をご提案します。" },
      { title: "自分らしさを残す補正", text: "肌色や色調、背景を整えながら、本来の印象と表情を大切にします。" },
      { title: "公開範囲を明確に", text: "ポートフォリオ使用の可否と範囲を撮影前に確認します。非公開撮影も可能です。" },
    ],
    sessionsEyebrow: "SESSIONS",
    sessionsTitle: "写真を必要とする理由から、一緒に考えます。",
    sessionsDescription: "決まったプランに当てはめるのではなく、目的、場所、移動、レタッチ範囲に合わせて内容をご案内します。",
    sessions: [
      { icon: UserRound, name: "Portrait Snap", title: "個人ポートレート", time: "約60分", text: "プロフィール、SNS、今の自分を残すための自然なポートレート撮影です。", tags: ["プロフィール", "デイリー", "SNS"] },
      { icon: UsersRound, name: "Couple Snap", title: "カップル・デート撮影", time: "約60〜90分", text: "決まったポーズより、歩きながら会話する二人らしい流れを撮影します。", tags: ["デート", "記念日", "屋外"] },
      { icon: Sparkles, name: "Portfolio", title: "プロフィール・ブランディング", time: "約60〜90分", text: "ウェブサイト、ブログ、仕事用プロフィールの目的に合わせて方向性を整理します。", tags: ["ブランディング", "仕事用", "コンセプト"] },
      { icon: Heart, name: "Collaboration", title: "ポートフォリオコラボ", time: "日程相談", text: "双方の方向性が合う場合、コンセプトと使用範囲を確認したうえでTFP撮影を行います。", tags: ["TFP", "モデル", "使用範囲相談"] },
    ],
    processEyebrow: "PROCESS",
    processTitle: "相談から納品まで、わかりやすく丁寧に。",
    process: [
      { number: "01", title: "お問い合わせ", text: "希望日、エリア、目的、気になる雰囲気をお送りください。" },
      { number: "02", title: "方向性の決定", text: "移動、光、衣装、使用目的を考えながら場所とコンセプトを決めます。" },
      { number: "03", title: "撮影", text: "会話と自然な動きの中で、表情やポーズを丁寧にご案内します。" },
      { number: "04", title: "セレクト・納品", text: "候補写真を確認後、選んだ写真を自然にレタッチしてオンラインで納品します。" },
    ],
    reviewsEyebrow: "REAL REVIEWS",
    reviewsTitle: "写真と一緒に残る、撮影時間の記憶",
    reviewsDescription: "実際に撮影した方からいただいた声です。完成写真だけでなく、現場の雰囲気ややり取りもご確認ください。",
    reviewOriginal: "レビュー原文を見る",
    moreReviews: "もっと見る",
    aboutEyebrow: "ABOUT PHOTOGRAPHER",
    aboutTitle: "写真より先に、人がリラックスできる瞬間を大切にしています。",
    aboutText: "365 Daily Snapでは、同じポーズを繰り返すのではなく、会話や動きの中からその人らしい表情を探します。準備、撮影中のディレクション、セレクト、納品まで、初めての方にもわかりやすくご案内します。",
    aboutFacts: ["ソウル首都圏中心", "平日夜・週末", "個人・カップル・プロフィール", "東京指定日程"],
    faqEyebrow: "FAQ",
    faqTitle: "撮影前によくあるご質問",
    faqs: [
      { q: "撮影が初めてでも大丈夫ですか？", a: "もちろんです。ポーズを準備する必要はなく、歩く方向、目線、手の位置など小さな動きからご案内します。" },
      { q: "元データも受け取れますか？", a: "元データの共有範囲は撮影内容に応じて事前にご案内します。候補写真からお好きなカットを選ぶ方法も可能です。" },
      { q: "レタッチの範囲は？", a: "明るさ、色、肌色、背景の気になる部分を自然に整えます。顔や体型を大きく変える加工は基本レタッチに含みません。" },
      { q: "非公開撮影は可能ですか？", a: "可能です。全体公開、一部のみ公開、非公開からご希望の範囲を撮影前に確認します。" },
      { q: "雨の場合はどうなりますか？", a: "前日の天気予報を確認し、室内への変更または日程の再調整をご相談します。" },
      { q: "撮影場所を提案してもらえますか？", a: "希望する色味、衣装、移動可能なエリア、撮影目的に合わせて場所と時間をご提案します。" },
    ],
    inquiryEyebrow: "CONTACT",
    inquiryTitle: "イメージがまだ曖昧でも大丈夫です。",
    inquiryDescription: "希望日、エリア、撮影目的だけ先にお知らせください。必要な写真と雰囲気は、相談しながら一緒に整理します。",
    quick: "簡単問い合わせ",
    detail: "詳細問い合わせ",
    step: "ステップ",
    next: "次へ",
    previous: "戻る",
    submit: "送信する",
    sending: "送信中",
    form: { type: "撮影タイプ", name: "お名前 / ニックネーム", contactMethod: "連絡方法", contact: "連絡先", date: "希望日", region: "希望エリア", mood: "希望イメージ", purpose: "撮影目的", people: "人数", privacy: "公開範囲", reference: "参考画像", message: "その他", consent: "お問い合わせに必要な個人情報の収集・利用に同意します。" },
    placeholders: { name: "お名前またはニックネーム", contact: "Instagram ID、Kakao ID、電話番号、メール", date: "例：7月第2週の週末午後", region: "例：ソンス、ヨンナム、イルサン", mood: "例：自然なフィルム感、夜のシネマティック", purpose: "例：プロフィール、記念日、ポートフォリオ", message: "不安な点や必ず残したいシーンをご記入ください。" },
    types: ["個人", "カップル", "プロフィール・ブランディング", "ポートフォリオコラボ", "相談して決定"],
    contactMethods: ["Instagram DM", "KakaoTalk", "電話・SMS", "メール"],
    privacyOptions: ["相談して決定", "公開可能", "一部のみ公開", "非公開希望"],
    uploadHint: "最大3枚、1枚8MB以下",
    consentDetail: "収集項目：名前、連絡先、撮影内容 · 目的：撮影相談と日程調整 · 保管：相談終了後1年、または削除依頼時",
    sent: "お問い合わせを受け付けました。内容を確認後、ご指定の連絡方法で返信します。",
    fallbackTitle: "内容をコピーしました。",
    fallbackText: "現在ウェブ保存機能が接続されていないため、内容をクリップボードにコピーしました。KakaoTalkまたはInstagram DMに貼り付けてください。",
    openKakao: "KakaoTalkを開く",
    openInstagram: "Instagramを開く",
    validation: "必須項目と同意欄をご確認ください。",
    footerLine: "自然なポートレート · Seoul / Capital Area / Selected Tokyo Dates",
    privacy: "プライバシー",
    close: "閉じる",
    photoCount: "枚",
  },
  en: {
    languageName: "English",
    title: "365 Daily Snap | Seoul & Tokyo Portrait Photographer",
    description: "Natural portrait, profile and couple sessions in Seoul and the capital area, with selected Tokyo dates by arrangement.",
    nav: { work: "Work", sessions: "Sessions", reviews: "Reviews", about: "About", faq: "FAQ", contact: "Contact" },
    heroEyebrow: "SEOUL · CAPITAL AREA · TOKYO SELECTED DATES",
    heroTitle: "Let the moment feel like you,\nthen make it last.",
    heroDescription: "I photograph natural expressions found in conversation and movement rather than forcing a pose. First time in front of a camera? I will guide you calmly throughout the session.",
    heroPrimary: "View featured work",
    heroSecondary: "Plan a session",
    trust: ["First-session friendly", "Seoul & capital area", "Publishing agreed in advance"],
    workEyebrow: "FEATURED PROJECTS",
    workTitle: "More than a final frame—the atmosphere of the whole session.",
    workDescription: "Images from the same day are presented as one project, so you can see how light, place and expression come together.",
    viewProject: "View project",
    moreProjects: "Show more projects",
    lessProjects: "Show less",
    projectInquiry: "Ask about this mood",
    originalPost: "View on Instagram",
    whyEyebrow: "WHY 365 DAILY SNAP",
    whyTitle: "Good portraits begin with a comfortable session.",
    whyItems: [
      { title: "Natural, even if you feel awkward", text: "There is no need to memorize poses. I guide your pace, eye line and hand placement one step at a time." },
      { title: "A location that fits the mood", text: "Location and timing are suggested around your visual direction, travel route, season and available light." },
      { title: "Retouching that still looks like you", text: "Skin tone, color and background distractions are refined while your natural features and expression remain intact." },
      { title: "Clear publishing preferences", text: "Portfolio use is agreed before the shoot. Full, selected or private sessions are all possible." },
    ],
    sessionsEyebrow: "SESSIONS",
    sessionsTitle: "We begin with why you need the photographs.",
    sessionsDescription: "Rather than forcing every shoot into a fixed package, the final plan is shaped around purpose, location, travel time and retouching scope.",
    sessions: [
      { icon: UserRound, name: "Portrait Snap", title: "Personal portrait", time: "About 60 min", text: "Natural portraits for profiles, social media and a record of who you are now.", tags: ["Profile", "Daily", "Social"] },
      { icon: UsersRound, name: "Couple Snap", title: "Couple & date", time: "About 60–90 min", text: "Your connection is photographed through walking, talking and genuine movement rather than fixed poses.", tags: ["Date", "Anniversary", "Outdoor"] },
      { icon: Sparkles, name: "Portfolio", title: "Profile & branding", time: "About 60–90 min", text: "A visual direction tailored to your website, blog, introduction page or professional profile.", tags: ["Branding", "Professional", "Concept"] },
      { icon: Heart, name: "Collaboration", title: "Portfolio collaboration", time: "By agreement", text: "Selective TFP collaborations are available when the concept, portfolio direction and usage terms align.", tags: ["TFP", "Model", "Usage agreed"] },
    ],
    processEyebrow: "PROCESS",
    processTitle: "A simple process, with clear guidance from inquiry to delivery.",
    process: [
      { number: "01", title: "Inquiry", text: "Share your preferred date, area, purpose and any visual direction you have in mind." },
      { number: "02", title: "Planning", text: "We confirm the location and concept around travel, light, wardrobe and how the images will be used." },
      { number: "03", title: "Session", text: "We talk and move naturally while I guide expression, posture and pace throughout the shoot." },
      { number: "04", title: "Select & deliver", text: "After reviewing the candidates, selected images are naturally retouched and delivered online." },
    ],
    reviewsEyebrow: "REAL REVIEWS",
    reviewsTitle: "The atmosphere of the session stays with the photographs.",
    reviewsDescription: "Words from people I have photographed, covering not only the final images but also the communication and experience on set.",
    reviewOriginal: "View original review",
    moreReviews: "Show more reviews",
    aboutEyebrow: "ABOUT PHOTOGRAPHER",
    aboutTitle: "I wait for the person to feel comfortable before asking the photograph to happen.",
    aboutText: "365 Daily Snap looks for natural expressions in conversation and movement instead of repeating fixed poses. From preparation and on-set direction to selection and delivery, every step is explained clearly so first-time clients can feel at ease.",
    aboutFacts: ["Seoul & capital area", "Evenings & weekends", "Portrait · Couple · Profile", "Selected Tokyo dates"],
    faqEyebrow: "FAQ",
    faqTitle: "What people usually ask before booking",
    faqs: [
      { q: "Is it okay if this is my first photo session?", a: "Absolutely. You do not need to prepare poses. I guide small movements such as walking direction, eye line and hand placement on location." },
      { q: "Can I receive the original files?", a: "The original-file delivery scope is explained in advance according to the session type. When appropriate, a candidate gallery can be shared so you can choose your preferred frames." },
      { q: "How much retouching is included?", a: "Exposure, color, skin tone and distracting background elements are refined naturally. Major changes to face shape or body proportions are not included in the standard edit." },
      { q: "Can the session remain private?", a: "Yes. Full portfolio use, selected images only or a fully private session can be agreed before the shoot." },
      { q: "What happens if it rains?", a: "We review the forecast the day before and either move indoors or reschedule together." },
      { q: "Can you recommend a location?", a: "Yes. I suggest locations and timing based on your preferred mood, wardrobe, travel area and intended use." },
    ],
    inquiryEyebrow: "CONTACT",
    inquiryTitle: "Your concept does not need to be fully formed yet.",
    inquiryDescription: "Start with your preferred date, area and purpose. We can shape the mood and must-have images together through conversation.",
    quick: "Quick inquiry",
    detail: "Detailed inquiry",
    step: "Step",
    next: "Next",
    previous: "Back",
    submit: "Send inquiry",
    sending: "Sending",
    form: { type: "Session type", name: "Name / nickname", contactMethod: "Contact method", contact: "Contact or account", date: "Preferred date", region: "Preferred area", mood: "Desired mood", purpose: "Purpose", people: "Number of people", privacy: "Publishing preference", reference: "Reference images", message: "Additional notes", consent: "I consent to the collection and use of personal information for this inquiry." },
    placeholders: { name: "Your name or nickname", contact: "Instagram ID, Kakao ID, phone or email", date: "e.g. second weekend of July, afternoon", region: "e.g. Seongsu, Yeonnam, Ilsan", mood: "e.g. understated film mood, cinematic night", purpose: "e.g. personal profile, anniversary, portfolio", message: "Share any concerns or must-have moments." },
    types: ["Personal portrait", "Couple", "Profile & branding", "Portfolio collaboration", "Decide after consultation"],
    contactMethods: ["Instagram DM", "KakaoTalk", "Phone / SMS", "Email"],
    privacyOptions: ["Decide after consultation", "Portfolio use allowed", "Selected images only", "Private"],
    uploadHint: "Up to 3 images, 8MB each",
    consentDetail: "Collected: name, contact and session request · Purpose: consultation and scheduling · Retention: one year after consultation or deleted upon request",
    sent: "Your inquiry has been received. I will review it and reply through your selected contact method.",
    fallbackTitle: "Your inquiry was copied.",
    fallbackText: "The web database is not connected, so the message was copied to your clipboard. Paste it into KakaoTalk or Instagram DM.",
    openKakao: "Open KakaoTalk",
    openInstagram: "Open Instagram",
    validation: "Please complete the required fields and consent checkbox.",
    footerLine: "Natural portraits · Seoul / Capital Area / Selected Tokyo Dates",
    privacy: "Privacy notice",
    close: "Close",
    photoCount: "photos",
  },
};