import { Heart, Sparkles, UserRound, UsersRound } from "lucide-react";

export const COPY = {
  ko: {
    languageName: "한국어",
    title: "365 Daily Snap | 서울 인물 스냅·프로필 촬영",
    description: "서울·수도권에서 자연스러운 인물 스냅, 프로필, 커플 촬영과 모델 포트폴리오 협업을 진행합니다.",
    nav: { work: "대표 작업", sessions: "촬영 구성", reviews: "후기", about: "작가 소개", faq: "FAQ", contact: "문의" },
    heroEyebrow: "SEOUL · CAPITAL AREA · TOKYO SELECTED DATES",
    heroTitle: "평범한 하루도,\n오래 기억될 장면으로.",
    heroDescription: "서울·수도권에서 자연스러운 인물 스냅을 촬영합니다. 사진이 처음이어도 포즈와 시선을 편안하게 안내해드립니다.",
    heroPrimary: "대표 작업 보기",
    heroSecondary: "촬영 문의하기",
    trust: ["평일 저녁·주말", "개인·커플·프로필", "TFP 협업 가능"],
    workEyebrow: "FEATURED PROJECTS",
    workTitle: "사진 한 장보다, 촬영의 흐름을 보여드립니다.",
    workDescription: "대표 사진만 나열하지 않고 같은 날의 분위기와 장면을 하나의 프로젝트로 묶었습니다.",
    viewProject: "프로젝트 보기",
    moreProjects: "프로젝트 더 보기",
    lessProjects: "접기",
    projectInquiry: "이 분위기로 문의하기",
    originalPost: "Instagram 원본 보기",
    whyEyebrow: "WHY 365 DAILY SNAP",
    whyTitle: "촬영이 어색한 순간부터 함께 정리합니다.",
    whyItems: [
      { title: "처음이어도 괜찮습니다", text: "걷기, 시선, 손 위치처럼 작은 움직임부터 안내합니다." },
      { title: "장소와 시간대를 함께 고릅니다", text: "원하는 분위기와 이동 동선을 기준으로 촬영 장소를 제안합니다." },
      { title: "과하지 않은 자연스러운 보정", text: "피부톤과 색감, 배경을 정돈하되 본래의 인상은 유지합니다." },
      { title: "공개 범위를 먼저 확인합니다", text: "포트폴리오 공개, 일부 공개, 비공개 요청을 촬영 전에 조율합니다." },
    ],
    sessionsEyebrow: "SESSIONS",
    sessionsTitle: "필요한 목적에 맞춰 촬영합니다.",
    sessionsDescription: "정확한 비용과 제공 컷은 촬영 시간, 장소 이동, 보정 범위에 따라 상담 후 안내합니다.",
    sessions: [
      { icon: UserRound, name: "Portrait Snap", title: "개인 인물 스냅", time: "약 60분", text: "프로필, SNS, 일상 기록을 위한 자연스러운 개인 촬영입니다.", tags: ["개인 프로필", "데일리", "SNS"] },
      { icon: UsersRound, name: "Couple Snap", title: "커플·데이트 스냅", time: "약 60~90분", text: "과한 연출보다 두 사람의 편안한 움직임과 표정을 담습니다.", tags: ["데이트", "기념일", "야외"] },
      { icon: Sparkles, name: "Portfolio", title: "프로필·브랜딩", time: "약 60~90분", text: "소개 페이지, 블로그, 업무용 프로필에 맞춰 이미지 방향을 설계합니다.", tags: ["브랜딩", "업무 프로필", "콘셉트"] },
      { icon: Heart, name: "Collaboration", title: "포트폴리오 협업", time: "일정 협의", text: "서로 필요한 작업 방향이 맞는 경우 상호무페이·TFP 촬영을 진행합니다.", tags: ["TFP", "모델 협업", "공개 범위 협의"] },
    ],
    processEyebrow: "PROCESS",
    processTitle: "복잡하지 않게, 네 단계로 진행합니다.",
    process: [
      { number: "01", title: "문의", text: "희망 날짜, 지역, 촬영 목적과 원하는 분위기를 보내주세요." },
      { number: "02", title: "일정·장소 확정", text: "이동 동선과 시간대에 맞춰 촬영 장소와 콘셉트를 정합니다." },
      { number: "03", title: "촬영", text: "대화하며 자연스러운 표정과 움직임을 함께 만들어갑니다." },
      { number: "04", title: "셀렉·보정·전달", text: "후보 컷을 확인하고 선택한 사진을 자연스럽게 보정해 전달합니다." },
    ],
    reviewsEyebrow: "REAL REVIEWS",
    reviewsTitle: "함께 촬영한 분들의 실제 후기",
    reviewsDescription: "결과물뿐 아니라 촬영 분위기와 소통 과정까지 확인해보세요.",
    reviewOriginal: "후기 원본 보기",
    moreReviews: "후기 더 보기",
    aboutEyebrow: "ABOUT PHOTOGRAPHER",
    aboutTitle: "안녕하세요. 365 Daily Snap의 김경민입니다.",
    aboutText: "정해진 포즈를 반복하기보다 대화와 움직임 속에서 자연스러운 표정을 담습니다. 사진이 익숙하지 않은 분도 부담 없이 촬영할 수 있도록 포즈와 시선을 단계별로 안내합니다.",
    aboutFacts: ["서울·수도권 중심", "평일 저녁·주말 촬영", "개인·커플·프로필", "도쿄 선택 일정"],
    faqEyebrow: "FAQ",
    faqTitle: "촬영 전에 많이 묻는 내용",
    faqs: [
      { q: "사진이 처음이어도 괜찮나요?", a: "괜찮습니다. 정해진 포즈를 외울 필요 없이 걷기, 시선, 손 위치부터 현장에서 안내합니다." },
      { q: "원본도 받을 수 있나요?", a: "촬영 형태에 따라 원본 전달 범위를 사전에 안내합니다. 후보 컷을 공유한 뒤 원하는 사진을 선택하는 방식으로 진행할 수 있습니다." },
      { q: "보정은 어디까지 진행하나요?", a: "색감, 피부톤, 노출, 배경의 방해 요소를 자연스럽게 정리합니다. 얼굴형을 크게 바꾸는 과도한 변형은 기본 보정에 포함하지 않습니다." },
      { q: "비공개 촬영도 가능한가요?", a: "가능합니다. 포트폴리오 공개 가능 여부와 공개 범위는 촬영 전에 별도로 확인합니다." },
      { q: "비가 오면 어떻게 하나요?", a: "실내 장소로 변경하거나 일정을 조정합니다. 촬영 전날 예보를 기준으로 함께 결정합니다." },
      { q: "촬영 장소도 추천받을 수 있나요?", a: "원하는 색감, 의상, 이동 가능한 지역을 바탕으로 장소와 적절한 시간대를 제안합니다." },
    ],
    inquiryEyebrow: "CONTACT",
    inquiryTitle: "30초 빠른 문의부터 상세 상담까지",
    inquiryDescription: "필수 정보만 먼저 남기고, 촬영 방향은 이후 대화로 정리해도 괜찮습니다.",
    quick: "빠른 문의",
    detail: "상세 문의",
    step: "단계",
    next: "다음",
    previous: "이전",
    submit: "문의 보내기",
    sending: "문의 전송 중",
    form: {
      type: "촬영 유형",
      name: "이름 / 닉네임",
      contactMethod: "연락 방법",
      contact: "연락처 또는 계정",
      date: "희망 날짜",
      region: "희망 지역",
      mood: "원하는 분위기",
      purpose: "촬영 목적",
      people: "인원 수",
      privacy: "사진 공개 범위",
      reference: "참고 이미지",
      message: "추가 요청",
      consent: "문의 접수를 위한 개인정보 수집·이용에 동의합니다.",
    },
    placeholders: {
      name: "성함 또는 닉네임",
      contact: "@Instagram ID, 카카오톡 ID, 전화번호 또는 이메일",
      date: "예: 7월 둘째 주 주말 오후",
      region: "예: 성수, 연남, 일산",
      mood: "예: 자연스러운 필름 느낌, 야간 시네마틱",
      purpose: "예: 개인 프로필, 커플 기념일, 포트폴리오",
      message: "걱정되는 점이나 꼭 원하는 장면을 적어주세요.",
    },
    types: ["개인 인물", "커플", "프로필·브랜딩", "포트폴리오 협업", "상담 후 결정"],
    contactMethods: ["Instagram DM", "카카오톡", "문자·전화", "이메일"],
    privacyOptions: ["상담 후 결정", "전체 공개 가능", "일부 컷만 공개", "비공개 희망"],
    uploadHint: "최대 3장, 장당 8MB 이하",
    consentDetail: "수집 항목: 이름, 연락처, 촬영 요청 정보 · 목적: 촬영 상담 및 일정 조율 · 보관: 상담 종료 후 1년 또는 요청 시 즉시 삭제",
    sent: "문의가 접수되었습니다. 확인 후 입력하신 연락처로 답변드리겠습니다.",
    fallbackTitle: "문의 내용을 복사했습니다.",
    fallbackText: "현재 웹 저장 기능이 연결되지 않아 문의 내용을 클립보드에 복사했습니다. 카카오톡 또는 Instagram DM에 붙여넣어 보내주세요.",
    openKakao: "카카오톡으로 이동",
    openInstagram: "Instagram으로 이동",
    validation: "필수 항목과 개인정보 동의를 확인해주세요.",
    footerLine: "자연스러운 인물 스냅 · 서울 / 수도권 / 도쿄 선택 일정",
    privacy: "개인정보 처리 안내",
    close: "닫기",
    photoCount: "장",
  },
  ja: {
    languageName: "日本語",
    title: "365 Daily Snap | ソウル・東京 ポートレート撮影",
    description: "ソウル首都圏を中心に、自然なポートレート、プロフィール、カップル撮影を行います。",
    nav: { work: "作品", sessions: "撮影プラン", reviews: "レビュー", about: "プロフィール", faq: "FAQ", contact: "お問い合わせ" },
    heroEyebrow: "SEOUL · CAPITAL AREA · TOKYO SELECTED DATES",
    heroTitle: "何気ない一日を、\n長く残る一枚に。",
    heroDescription: "ソウル首都圏を中心に、自然なポートレートを撮影します。撮影が初めての方にも、ポーズや目線を丁寧にご案内します。",
    heroPrimary: "作品を見る", heroSecondary: "撮影を問い合わせる", trust: ["平日夜・週末", "個人・カップル・プロフィール", "TFP相談可能"],
    workEyebrow: "FEATURED PROJECTS", workTitle: "一枚ではなく、撮影全体の空気を。", workDescription: "同じ日に撮影した写真を一つのプロジェクトとしてまとめています。", viewProject: "プロジェクトを見る", moreProjects: "もっと見る", lessProjects: "閉じる", projectInquiry: "この雰囲気で相談する", originalPost: "Instagramで見る",
    whyEyebrow: "WHY 365 DAILY SNAP", whyTitle: "撮影の不安から一緒に整えます。", whyItems: [
      { title: "初めてでも大丈夫", text: "歩き方、目線、手の位置から丁寧にご案内します。" }, { title: "場所と時間も提案", text: "希望する雰囲気と移動範囲に合わせて場所をご提案します。" }, { title: "自然なレタッチ", text: "肌色や色調を整えながら、本来の印象を残します。" }, { title: "公開範囲を事前確認", text: "全体公開、一部公開、非公開を撮影前に確認します。" }
    ],
    sessionsEyebrow: "SESSIONS", sessionsTitle: "目的に合わせた撮影プラン", sessionsDescription: "料金と納品枚数は撮影時間、移動、レタッチ範囲により個別にご案内します。",
    sessions: [
      { icon: UserRound, name: "Portrait Snap", title: "個人ポートレート", time: "約60分", text: "プロフィール、SNS、日常の記録に。", tags: ["プロフィール", "デイリー", "SNS"] },
      { icon: UsersRound, name: "Couple Snap", title: "カップル撮影", time: "約60〜90分", text: "二人らしい自然な動きと表情を撮影します。", tags: ["デート", "記念日", "屋外"] },
      { icon: Sparkles, name: "Portfolio", title: "プロフィール・ブランディング", time: "約60〜90分", text: "紹介ページや仕事用プロフィールに合わせて方向性を整理します。", tags: ["ブランディング", "仕事用", "コンセプト"] },
      { icon: Heart, name: "Collaboration", title: "ポートフォリオ協力", time: "日程相談", text: "方向性が合う場合、TFP撮影も行います。", tags: ["TFP", "モデル", "公開範囲相談"] },
    ],
    processEyebrow: "PROCESS", processTitle: "4つのステップで進みます。", process: [
      { number: "01", title: "お問い合わせ", text: "希望日、エリア、目的、イメージをお送りください。" }, { number: "02", title: "日程・場所の決定", text: "移動と時間帯に合わせて場所とコンセプトを決めます。" }, { number: "03", title: "撮影", text: "会話をしながら自然な表情と動きを引き出します。" }, { number: "04", title: "セレクト・納品", text: "選んだ写真を自然にレタッチし、オンラインで納品します。" }
    ],
    reviewsEyebrow: "REAL REVIEWS", reviewsTitle: "実際に撮影した方のレビュー", reviewsDescription: "写真だけでなく、撮影中の雰囲気やコミュニケーションもご確認ください。", reviewOriginal: "レビュー原文", moreReviews: "もっと見る",
    aboutEyebrow: "ABOUT PHOTOGRAPHER", aboutTitle: "365 Daily SnapのKim Kyungminです。", aboutText: "決まったポーズを繰り返すのではなく、会話と動きの中で自然な表情を残します。初めての方にもポーズや目線を段階的にご案内します。", aboutFacts: ["ソウル首都圏", "平日夜・週末", "個人・カップル", "東京選択日程"],
    faqEyebrow: "FAQ", faqTitle: "よくある質問", faqs: [
      { q: "撮影が初めてでも大丈夫ですか？", a: "大丈夫です。ポーズを覚える必要はなく、歩き方や目線からご案内します。" }, { q: "元データはもらえますか？", a: "撮影内容に応じて事前にご案内します。候補からお好きな写真を選ぶこともできます。" }, { q: "レタッチの範囲は？", a: "色、肌色、明るさ、背景を自然に整えます。顔立ちを大きく変える加工は基本に含みません。" }, { q: "非公開撮影は可能ですか？", a: "可能です。公開範囲は撮影前に確認します。" }, { q: "雨の場合は？", a: "室内への変更、または日程変更を前日の予報を見て相談します。" }, { q: "場所を提案してもらえますか？", a: "希望する色味、服装、移動範囲に合わせて場所と時間をご提案します。" }
    ],
    inquiryEyebrow: "CONTACT", inquiryTitle: "簡単な相談から詳しいお問い合わせまで", inquiryDescription: "必須情報だけ先に送り、詳しい内容は後から一緒に整理できます。", quick: "簡単問い合わせ", detail: "詳細問い合わせ", step: "ステップ", next: "次へ", previous: "戻る", submit: "送信する", sending: "送信中",
    form: { type: "撮影タイプ", name: "お名前 / ニックネーム", contactMethod: "連絡方法", contact: "連絡先", date: "希望日", region: "希望エリア", mood: "希望イメージ", purpose: "撮影目的", people: "人数", privacy: "公開範囲", reference: "参考画像", message: "その他", consent: "お問い合わせに必要な個人情報の収集・利用に同意します。" },
    placeholders: { name: "お名前またはニックネーム", contact: "Instagram ID、Kakao ID、電話番号、メール", date: "例：7月第2週の週末午後", region: "例：ソンス、ヨンナム、イルサン", mood: "例：自然なフィルム感、夜のシネマティック", purpose: "例：プロフィール、記念日、ポートフォリオ", message: "不安な点や希望するカットをご記入ください。" },
    types: ["個人", "カップル", "プロフィール・ブランディング", "ポートフォリオ協力", "相談して決定"], contactMethods: ["Instagram DM", "KakaoTalk", "電話・SMS", "メール"], privacyOptions: ["相談して決定", "公開可能", "一部のみ公開", "非公開希望"], uploadHint: "最大3枚、1枚8MB以下", consentDetail: "収集項目：名前、連絡先、撮影内容 · 目的：撮影相談と日程調整 · 保管：相談終了後1年、または削除依頼時", sent: "お問い合わせを受け付けました。確認後ご連絡します。", fallbackTitle: "内容をコピーしました。", fallbackText: "現在ウェブ保存機能が接続されていないため、内容をクリップボードにコピーしました。KakaoTalkまたはInstagram DMに貼り付けてください。", openKakao: "KakaoTalkを開く", openInstagram: "Instagramを開く", validation: "必須項目と同意欄をご確認ください。", footerLine: "自然なポートレート · Seoul / Tokyo", privacy: "プライバシー", close: "閉じる", photoCount: "枚",
  },
  en: {
    languageName: "English",
    title: "365 Daily Snap | Seoul & Tokyo Portrait Photographer",
    description: "Natural portrait, profile and couple sessions in Seoul, the capital area and selected Tokyo dates.",
    nav: { work: "Work", sessions: "Sessions", reviews: "Reviews", about: "About", faq: "FAQ", contact: "Contact" },
    heroEyebrow: "SEOUL · CAPITAL AREA · TOKYO SELECTED DATES", heroTitle: "Turn an ordinary day\ninto a lasting frame.", heroDescription: "Natural portrait sessions in Seoul and the capital area. First time in front of a camera? I will guide your pose, gaze and movement throughout the shoot.", heroPrimary: "View featured work", heroSecondary: "Plan a session", trust: ["Weekday evenings & weekends", "Portrait · Couple · Profile", "TFP collaboration available"],
    workEyebrow: "FEATURED PROJECTS", workTitle: "See the flow of a session, not just one frame.", workDescription: "Photos from the same shoot are grouped into projects so you can understand the full mood and story.", viewProject: "View project", moreProjects: "Show more projects", lessProjects: "Show less", projectInquiry: "Ask for this mood", originalPost: "View on Instagram",
    whyEyebrow: "WHY 365 DAILY SNAP", whyTitle: "We start by making the shoot feel comfortable.", whyItems: [
      { title: "Beginner-friendly direction", text: "I guide small movements such as walking, eye line and hand placement." }, { title: "Location and timing support", text: "Locations are suggested around your preferred mood and travel route." }, { title: "Natural retouching", text: "Skin tone, color and distractions are refined while keeping you recognizable." }, { title: "Clear publishing consent", text: "Full, partial or private use is agreed before the session." }
    ],
    sessionsEyebrow: "SESSIONS", sessionsTitle: "A session for the way you will use the photos.", sessionsDescription: "Final pricing and delivery count depend on session length, travel and retouching scope.",
    sessions: [
      { icon: UserRound, name: "Portrait Snap", title: "Personal portrait", time: "About 60 min", text: "Natural portraits for profiles, social media and personal memories.", tags: ["Profile", "Daily", "SNS"] },
      { icon: UsersRound, name: "Couple Snap", title: "Couple & date", time: "About 60–90 min", text: "Comfortable movement and genuine expressions over rigid posing.", tags: ["Date", "Anniversary", "Outdoor"] },
      { icon: Sparkles, name: "Portfolio", title: "Profile & branding", time: "About 60–90 min", text: "A visual direction for personal sites, blogs and professional profiles.", tags: ["Branding", "Professional", "Concept"] },
      { icon: Heart, name: "Collaboration", title: "Portfolio collaboration", time: "By agreement", text: "TFP sessions are available when both portfolios and concepts align.", tags: ["TFP", "Model", "Usage agreed"] },
    ],
    processEyebrow: "PROCESS", processTitle: "A clear four-step process.", process: [
      { number: "01", title: "Inquiry", text: "Share your preferred date, area, purpose and visual references." }, { number: "02", title: "Plan", text: "We confirm the location, timing and concept around your route." }, { number: "03", title: "Shoot", text: "We talk and move naturally while I guide your expression and pose." }, { number: "04", title: "Select & deliver", text: "Selected images are naturally retouched and delivered online." }
    ],
    reviewsEyebrow: "REAL REVIEWS", reviewsTitle: "Reviews from people I photographed", reviewsDescription: "See what the communication and atmosphere felt like, not only the final images.", reviewOriginal: "View original review", moreReviews: "Show more reviews",
    aboutEyebrow: "ABOUT PHOTOGRAPHER", aboutTitle: "Hi, I’m Kim Kyungmin of 365 Daily Snap.", aboutText: "Rather than repeating fixed poses, I look for natural expressions in conversation and movement. I guide first-time clients step by step so the session feels easy and unforced.", aboutFacts: ["Seoul & capital area", "Evenings & weekends", "Portrait · Couple · Profile", "Selected Tokyo dates"],
    faqEyebrow: "FAQ", faqTitle: "Common questions before a shoot", faqs: [
      { q: "Is it okay if this is my first photo session?", a: "Absolutely. You do not need to memorize poses. I guide walking, eye line and hand placement on location." }, { q: "Can I receive the original files?", a: "The delivery scope is agreed before the session. A selection gallery can be shared so you can choose your preferred frames." }, { q: "How much retouching is included?", a: "Color, skin tone, exposure and background distractions are refined naturally. Major face-shape alterations are not part of the standard edit." }, { q: "Can the session remain private?", a: "Yes. Full, partial or no portfolio use can be agreed before the shoot." }, { q: "What happens if it rains?", a: "We can switch to an indoor location or reschedule based on the forecast the day before." }, { q: "Can you recommend a location?", a: "Yes. I suggest locations and timing based on your outfit, preferred color palette and travel area." }
    ],
    inquiryEyebrow: "CONTACT", inquiryTitle: "Start with a 30-second inquiry or send full details", inquiryDescription: "You can send only the essentials first and refine the concept together afterwards.", quick: "Quick inquiry", detail: "Detailed inquiry", step: "Step", next: "Next", previous: "Back", submit: "Send inquiry", sending: "Sending",
    form: { type: "Session type", name: "Name / nickname", contactMethod: "Contact method", contact: "Contact or account", date: "Preferred date", region: "Preferred area", mood: "Desired mood", purpose: "Purpose", people: "Number of people", privacy: "Publishing preference", reference: "Reference images", message: "Additional notes", consent: "I consent to the collection and use of personal information for this inquiry." },
    placeholders: { name: "Your name or nickname", contact: "Instagram ID, Kakao ID, phone or email", date: "e.g. second weekend of July, afternoon", region: "e.g. Seongsu, Yeonnam, Ilsan", mood: "e.g. natural film look, cinematic night", purpose: "e.g. profile, anniversary, portfolio", message: "Share any concerns or must-have frames." },
    types: ["Personal portrait", "Couple", "Profile & branding", "Portfolio collaboration", "Decide after consultation"], contactMethods: ["Instagram DM", "KakaoTalk", "Phone / SMS", "Email"], privacyOptions: ["Decide after consultation", "Portfolio use allowed", "Selected images only", "Private"], uploadHint: "Up to 3 images, 8MB each", consentDetail: "Collected: name, contact and session request · Purpose: consultation and scheduling · Retention: one year after consultation or deleted upon request", sent: "Your inquiry has been received. I will reply through your selected contact method.", fallbackTitle: "Your inquiry was copied.", fallbackText: "The web database is not connected, so the message was copied to your clipboard. Paste it into KakaoTalk or Instagram DM.", openKakao: "Open KakaoTalk", openInstagram: "Open Instagram", validation: "Please complete the required fields and consent checkbox.", footerLine: "Natural portraits · Seoul / Capital Area / Selected Tokyo dates", privacy: "Privacy notice", close: "Close", photoCount: "photos",
  },
};
